# Generated by Django 4.2.1 on 2023-05-20 05:44

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("like", models.IntegerField(default=0)),
                ("title", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=20)),
                ("category", models.CharField(max_length=20)),
                ("address", models.ImageField(upload_to=app.models.photo_upload_path)),
            ],
        ),
    ]
